//
//	DatabaseHelper.java
//
//	Generated by DatabaseHelper.java.xslt on 08/11/2015.
//	DO NOT EDIT!
//
package com.dumma.flowback.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DatabaseHelper extends SQLiteOpenHelper {

    static final String DATABASE_NAME = "flowback.db";

    static final int DATABASE_VERSION = 1;

    public DatabaseHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(
              "CREATE TABLE " + Contract.TABLE_NAME +
              "(" +
              Contract.Columns._ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
              Contract.Columns.PRESSURE + " REAL, " +
              Contract.Columns.GAS+ " REAL, " +
              Contract.Columns.OIL + " REAL, " +
              Contract.Columns.WATER_RATE + " REAL, " +
              Contract.Columns.GAS_RATE+ " REAL, " +
              Contract.Columns.OIL_RATE + " REAL, " +
              Contract.Columns.CHOKE + " REAL, " +
              Contract.Columns.TIMESTAMP + " TEXT " +
              ")"
        );
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS " + Contract.TABLE_NAME);
        onCreate(db);
    }


    // add methods to get data with different time ranges
}
